export const weaponTypeOptions = [
  { value: "great-sword", label: "Great Sword" },
  { value: "long-sword", label: "Long Sword" },
  { value: "sword-and-shield", label: "Sword and Shield" },
  { value: "dual-blades", label: "Dual Blades" },
  { value: "hammer", label: "Hammer" },
  { value: "hunting-horn", label: "Hunting Horn" },
  { value: "lance", label: "Lance" },
  { value: "gunlance", label: "Gunlance" },
  { value: "switch-axe", label: "Switch Axe" },
  { value: "charge-blade", label: "Charge Blade" },
  { value: "insect-glaive", label: "Insect Glaive" },
  { value: "light-bowgun", label: "Light Bowgun" },
  { value: "heavy-bowgun", label: "Heavy Bowgun" },
  { value: "bow", label: "Bow" },
];
